spring:
  datasource:
    url: jdbc:h2:file:~/stationerycontrol-user;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: false
    console.path: /h2

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
