info:
  component: stationerycontrol-user-api

server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: stationerycontrol-user-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: sergioandresrr@ufps.edu.co
    password: ibpuzipuuzkcjzgk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
