#Component Info 
info:
  component: stationerycontrol-user-api

#Port - If 0 get random port
server:
  port: 8083

#Application Name
spring:
  application:
    name: stationerycontrol-user-api
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:file:~/stationerycontrol-user
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: false
    console.path: /h2
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#Eureka Instance ID
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
